public class VARIABLETYPES{
    public static void main(String[] args){
        //Variable Declaration
        int a = 10;
        int b = 28;
        
        int sum= a+b;
        System.out.println("Sum of a and b is: " + sum);
        
        int multi= a*b;
        System.out.println("Multiplication of a and b is: " + multi);

        int diff=b-a;
        System.out.println("Difference of a and b is: " + diff);
    }
}